const MATARIKI_STARS = [
        {
            id: 'matariki',
            name: 'Matariki',
            englishName: 'Alcyone',
            x: 400,
            y: 250,
            brightness: 0.9,
            color: '#FFD700',
            image: '1.jpg',
            meaning: 'The mother star who watches over her children. She signifies reflection, hope, our connection to the environment and the gathering of people for Matariki.',
            story: 'Matariki is the mother of all the stars in the constellation, the central figure who guides and nurtures her children. She represents the heart of the Matariki season - a time for reflection on the past year, hope for the future, and bringing whānau (family) and communities together.',
            cultural: 'During Matariki, Māori traditionally gather to share kai (food), tell stories of ancestors, and plan for the year ahead. Matariki teaches us about whakapapa (genealogy), connecting us to our tūpuna (ancestors) and future generations. Her brightness in the sky indicates the prosperity and wellbeing that the new year will bring.',
            connected: false,
            discovered: false
        },
        {
            id: 'pohutukawa',
            name: 'Pōhutukawa',
            englishName: 'Sterope',
            x: 320,
            y: 320,
            brightness: 0.8,
            color: '#DC143C',
            image: '2.jpg',
            meaning: 'Connected to those who have passed away. Pōhutukawa is the star for remembering loved ones who died in the past year.',
            story: 'Pōhutukawa is deeply connected to remembrance and honoring those who have passed on to Te Pō (the realm of darkness). This star guides us in sharing memories, telling stories of our tūpuna (ancestors), and ensuring their legacies live on through oral tradition.',
            cultural: 'Named after the sacred pōhutukawa tree that grows along coastlines, this star reminds us that death is part of life\'s natural cycle. During Matariki celebrations, whānau gather to share photos, stories, and memories of those who have died in the past year. Pōhutukawa teaches us that while people may leave the physical world, their wisdom, love, and mana (spiritual power) remain with us forever.',
            connected: false,
            discovered: false
        },
        {
            id: 'tupuanuku',
            name: 'Tupuānuku',
            englishName: 'Pleione',
            x: 270,
            y: 250,
            brightness: 0.7,
            color: '#8B4513',
            image: '3.jpg',
            meaning: 'Connected to food that grows in the ground - kumara, potato, and other root vegetables.',
            story: 'Tupuānuku governs all kai (food) that grows beneath the soil - kūmara (sweet potato), riwai (potato), taewa, pūhā, and other root vegetables. She connects us deeply to Papatūānuku (Earth Mother) and the nourishing power of the soil.',
            cultural: 'Root vegetables were vital to traditional Māori survival, especially kūmara brought by early Polynesian voyagers. Tupuānuku teaches us about the sacred relationship between people and land - we must care for the soil, and it will care for us. She reminds us that our ancestors\' mana is literally in the ground we walk on, and that food sovereignty begins with healthy soil.',
            connected: false,
            discovered: false
        },
        {
            id: 'tupuarangi',
            name: 'Tupuārangi',
            englishName: 'Atlas',
            x: 200,
            y: 300,
            brightness: 0.7,
            color: '#32CD32',
            image: '4.jpg',
            meaning: 'Connected to food that grows up in the trees - fruits, berries, and birds.',
            story: 'Tupuārangi oversees all kai that grows above ground - fruits from trees, berries, and the birds that nest in the canopy. He watches over the manu (birds) that were both food sources and spiritual messengers for Māori.',
            cultural: 'Traditional Māori harvested karaka berries, hīnau, and other native fruits, along with birds like kererū and tūī. Tupuārangi teaches us about the intricate balance of forest ecosystems - birds spread seeds, trees provide shelter and food, and everything is connected. He reminds us that food from above ground connects us to Ranginui (Sky Father) and the realm of the heavens.',
            connected: false,
            discovered: false
        },
        {
            id: 'waitii',
            name: 'Waitī',
            englishName: 'Maia',
            x: 120,
            y: 200,
            brightness: 0.6,
            color: '#00CED1',
            image: '5.jpg',
            meaning: 'Associated with fresh water - streams, rivers and lakes. Waitī determines the success of freshwater fishing.',
            story: 'Waitī is the guardian of all freshwater sources - the awa (rivers), roto (lakes), and springs that provide life to the land. She watches over the native fish like kōura (freshwater crayfish), kōkopu, and tuna (eels) that live in these waters.',
            cultural: 'Fresh water is taonga (treasure) in Māori culture, essential for drinking, cooking, and spiritual cleansing. Waitī reminds us to protect our waterways from pollution and to fish sustainably. Traditional Māori would read Waitī\'s brightness to determine if the coming season would bring good freshwater fishing and healthy river systems.',
            connected: false,
            discovered: false
        },
        {
            id: 'waita',
            name: 'Waitā',
            englishName: 'Taygeta',
            x: 600,
            y: 220,
            brightness: 0.6,
            color: '#4169E1',
            image: '6.jpg',
            meaning: 'Associated with salt water and determines the success of fishing in the sea.',
            story: 'Waitā governs the moana (ocean) and all kai moana (seafood) within it. He oversees the abundance of fish, shellfish, and sea vegetables that coastal Māori communities depend on for sustenance.',
            cultural: 'The ocean provides kaimoana like pāua, kina, kōura, snapper, and kelp - all vital to Māori cuisine and culture. Waitā teaches respect for the sea\'s mauri (life force) and the importance of sustainable fishing practices. His appearance in the sky signals whether the ocean will provide bountifully in the coming year.',
            connected: false,
            discovered: false
        },
        {
            id: 'waipuna-a-rangi',
            name: 'Waipuna-ā-rangi',
            englishName: 'Electra',
            x: 680,
            y: 150,
            brightness: 0.6,
            color: '#87CEEB',
            image: '7.jpg',
            meaning: 'Associated with rain. Waipuna-ā-rangi determines the amount of rainfall for the year ahead.',
            story: 'Waipuna-ā-rangi controls the waters that fall from the heavens - ua (rain), snow, and dew. She is the divine source that replenishes the earth, fills the rivers, and nourishes all growing things from the sky above.',
            cultural: 'Rain is essential for the mauri (life force) of Papatūānuku (Earth Mother). Waipuna-ā-rangi reminds us that water connects all life - from the tiniest insects to the mighty kauri trees. Traditional Māori would observe her brightness to predict drought or abundant rains, planning their planting and harvesting accordingly.',
            connected: false,
            discovered: false
        },
        {
            id: 'ururangi',
            name: 'Ururangi',
            englishName: 'Merope',
            x: 320,
            y: 160,
            brightness: 0.5,
            color: '#9370DB',
            image: '8.jpg',
            meaning: 'Associated with the winds. Ururangi determines the nature of the winds for the coming year.',
            story: 'Ururangi commands all the hauhunga (winds) - from gentle breezes to powerful gales. He carries the breath of Ranginui (Sky Father) across the land, bringing change, movement, and the life-giving force of air itself.',
            cultural: 'Wind was crucial for Māori navigation across Te Moana-nui-a-Kiwa (Pacific Ocean). Ururangi taught navigators to read wind patterns, predict storms, and harness the wind\'s power for ocean voyaging. He also governs the winds that spread seeds, pollinate plants, and bring seasonal weather changes. Ururangi reminds us that change is natural and necessary - like wind reshaping the landscape, we too must adapt and flow with life\'s changes.',
            connected: false,
            discovered: false
        },
        {
            id: 'hiwa-i-te-rangi',
            name: 'Hiwa-i-te-rangi',
            englishName: 'Celaeno',
            x: 160,
            y: 240,
            brightness: 0.4,
            color: '#FF69B4',
            image: '9.jpg',
            meaning: 'The wishing star. Connected to dreams, aspirations, and hopes for the future. The youngest star in the constellation.',
            story: 'Hiwa-i-te-rangi is the youngest of Matariki\'s children, embodying our deepest hopes, dreams, and aspirations. She is the star we turn to when making wishes for ourselves, our whānau, and our communities for the year ahead.',
            cultural: 'As the wishing star, Hiwa-i-te-rangi connects us to our future potential and the power of intention. During Matariki, people share their hopes and dreams with her - from personal goals to community aspirations. She teaches us that dreams require both hope and action, and that the youngest voices often carry the most powerful visions for positive change. Hiwa-i-te-rangi reminds us to nurture the dreams of rangatahi (young people) and to never stop believing in transformation.',
            connected: false,
            discovered: false
        }
];

const CONSTELLATION_CONNECTIONS = [
    ['matariki', 'pohutukawa'],
    ['matariki', 'waitii'],
    ['matariki', 'waita'],
    ['matariki', 'waipuna-a-rangi'],
    ['matariki', 'tupuanuku'],
    ['matariki', 'tupuarangi'],
    ['matariki', 'ururangi'],
    ['pohutukawa', 'waitii'],
    ['waita', 'tupuanuku'],
    ['tupuanuku', 'tupuarangi'],
    ['tupuarangi', 'ururangi'],
    ['waipuna-a-rangi', 'tupuarangi'],
    ['hiwa-i-te-rangi', 'waipuna-a-rangi'],
    ['hiwa-i-te-rangi', 'waitii']
];

const BACKGROUND_STARS = [
    { x: 50, y: 100, brightness: 0.4 },
    { x: 150, y: 80, brightness: 0.5 },
    { x: 250, y: 120, brightness: 0.35 },
    { x: 750, y: 150, brightness: 0.4 },
    { x: 700, y: 300, brightness: 0.5 },
    { x: 750, y: 400, brightness: 0.35 },
    { x: 80, y: 400, brightness: 0.4 },
    { x: 150, y: 450, brightness: 0.35 },
    { x: 650, y: 500, brightness: 0.5 },
    { x: 750, y: 50, brightness: 0.4 },
    { x: 30, y: 300, brightness: 0.35 },
    { x: 720, y: 200, brightness: 0.4 },
    { x: 90, y: 180, brightness: 0.35 },
    { x: 250, y: 400, brightness: 0.4 },
    { x: 550, y: 450, brightness: 0.35 },
    { x: 60, y: 500, brightness: 0.5 },
    { x: 650, y: 100, brightness: 0.4 },
    { x: 580, y: 350, brightness: 0.35 },
    { x: 250, y: 50, brightness: 0.4 },
    { x: 500, y: 500, brightness: 0.35 },
    // Additional background stars for atmosphere
    { x: 100, y: 150, brightness: 0.25 },
    { x: 350, y: 80, brightness: 0.3 },
    { x: 450, y: 120, brightness: 0.25 },
    { x: 550, y: 90, brightness: 0.28 },
    { x: 180, y: 350, brightness: 0.25 },
    { x: 420, y: 380, brightness: 0.3 },
    { x: 520, y: 320, brightness: 0.25 },
    { x: 380, y: 450, brightness: 0.28 },
    { x: 680, y: 380, brightness: 0.25 },
    { x: 120, y: 50, brightness: 0.3 },
    { x: 720, y: 120, brightness: 0.25 },
    { x: 650, y: 250, brightness: 0.28 },
    { x: 50, y: 200, brightness: 0.25 },
    { x: 750, y: 320, brightness: 0.3 },
    { x: 300, y: 500, brightness: 0.25 },
    { x: 450, y: 50, brightness: 0.28 },
    { x: 580, y: 180, brightness: 0.25 },
    { x: 220, y: 280, brightness: 0.3 },
    { x: 480, y: 280, brightness: 0.25 },
    { x: 350, y: 200, brightness: 0.28 },
    { x: 150, y: 320, brightness: 0.25 },
    { x: 550, y: 250, brightness: 0.3 },
    { x: 80, y: 350, brightness: 0.25 },
    { x: 680, y: 150, brightness: 0.28 },
    { x: 400, y: 500, brightness: 0.25 },
    { x: 200, y: 150, brightness: 0.3 },
    { x: 600, y: 350, brightness: 0.25 },
    { x: 300, y: 350, brightness: 0.28 },
    { x: 500, y: 200, brightness: 0.25 },
    { x: 120, y: 280, brightness: 0.3 }
];